-- Create Venues table
CREATE TABLE IF NOT EXISTS venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  lat FLOAT,
  lng FLOAT,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  website TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Organizers table
CREATE TABLE IF NOT EXISTS organizers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  description TEXT,
  contact_email TEXT,
  social_links JSONB, -- { "instagram": "...", "twitter": "..." }
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Tags table
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('category', 'mood', 'other')),
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Update Events table
ALTER TABLE events 
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS venue_id BIGINT REFERENCES venues(id),
ADD COLUMN IF NOT EXISTS organizer_id BIGINT REFERENCES organizers(id),
ADD COLUMN IF NOT EXISTS rules TEXT, -- Good to know info
ADD COLUMN IF NOT EXISTS source_url TEXT, -- For scraping reference
ADD COLUMN IF NOT EXISTS ticket_details JSONB, -- Array of ticket options {name, price, status}
ADD COLUMN IF NOT EXISTS tags TEXT[]; -- Array of tag names or IDs

-- Create index on venue_id
CREATE INDEX IF NOT EXISTS idx_events_venue_id ON events(venue_id);

-- Add min_price column for filtering
ALTER TABLE events 
ADD COLUMN IF NOT EXISTS min_price INTEGER;

-- AI Enrichment Columns
ALTER TABLE events 
ADD COLUMN IF NOT EXISTS summary TEXT,
ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
ADD COLUMN IF NOT EXISTS ai_mood TEXT,
ADD COLUMN IF NOT EXISTS is_ai_processed BOOLEAN DEFAULT FALSE;
-- Phase 3: Engagement
CREATE TABLE IF NOT EXISTS follows (
  user_id UUID REFERENCES auth.users(id),
  entity_type TEXT, -- 'venue', 'organizer', 'category'
  entity_id TEXT, -- For venue/organizer name or ID
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, entity_type, entity_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  title TEXT,
  message TEXT,
  link TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Phase 3: Automatic Notifications Trigger
CREATE OR REPLACE FUNCTION handle_new_event_notification() 
RETURNS TRIGGER AS $$
BEGIN
  -- Notify users following the venue
  INSERT INTO notifications (user_id, title, message, link)
  SELECT 
    f.user_id,
    'Yeppuda! Yeni Etkinlik: ' || NEW.venue_name,
    NEW.title || ' etkinliği eklendi! Biletler tükenmeden göz at.',
    '/?event_id=' || NEW.id
  FROM follows f
  WHERE f.entity_type = 'venue' AND f.entity_id = NEW.venue_name;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_event_created ON events;
CREATE TRIGGER on_event_created
AFTER INSERT ON events
FOR EACH ROW
EXECUTE FUNCTION handle_new_event_notification();

-- Phase 4: System Health & Analytics
CREATE TABLE IF NOT EXISTS scraper_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scraper_name TEXT NOT NULL,
  status TEXT CHECK (status IN ('running', 'success', 'failed')),
  events_count INTEGER DEFAULT 0,
  error_message TEXT,
  duration_ms INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add column for cached images
ALTER TABLE events
ADD COLUMN IF NOT EXISTS local_image_url TEXT;

-- Event Clicks Tracking
CREATE TABLE IF NOT EXISTS event_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  click_type TEXT CHECK (click_type IN ('view', 'ticket', 'directions', 'share', 'calendar', 'restaurant')),
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_clicks_event_id ON event_clicks(event_id);
CREATE INDEX IF NOT EXISTS idx_event_clicks_created_at ON event_clicks(created_at);

-- Event Suggestions (user submitted)
CREATE TABLE IF NOT EXISTS event_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  event_url TEXT,
  notes TEXT,
  contact_email TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Phase 5: User Reviews
CREATE TABLE IF NOT EXISTS event_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5), -- 1-5 yıldız
  comment TEXT,
  is_verified BOOLEAN DEFAULT FALSE, -- Kullanıcı gerçekten katıldı mı?
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, user_id) -- Her kullanıcı bir etkinliğe tek yorum yapabilir
);

CREATE INDEX IF NOT EXISTS idx_event_reviews_event_id ON event_reviews(event_id);
CREATE INDEX IF NOT EXISTS idx_event_reviews_status ON event_reviews(status);

-- Average rating view
CREATE OR REPLACE VIEW event_ratings AS
SELECT 
  event_id,
  COUNT(*) as review_count,
  ROUND(AVG(rating)::numeric, 1) as avg_rating
FROM event_reviews
WHERE status = 'approved'
GROUP BY event_id;

-- =============================================
-- PHASE 6: MULTI-SOURCE TICKETS & VENUE URLS
-- =============================================

-- Add ticket_sources to events - different providers for same event
-- Format: [{"source": "bubilet", "url": "...", "price": "250 TL"}, {"source": "biletinial", "url": "...", "price": "280 TL"}]
ALTER TABLE events 
ADD COLUMN IF NOT EXISTS ticket_sources JSONB DEFAULT '[]'::jsonb;

-- Add maps_url to venues for easier coordinate extraction
ALTER TABLE venues
ADD COLUMN IF NOT EXISTS maps_url TEXT;

-- Add city column to venues for filtering
ALTER TABLE venues
ADD COLUMN IF NOT EXISTS city TEXT;

-- =============================================
-- PHASE 7: FEATURED EVENTS & PROMOTIONS
-- =============================================

-- Add featured/promoted columns to events
ALTER TABLE events
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS featured_until TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS feature_priority INTEGER DEFAULT 0, -- Higher = more prominent
ADD COLUMN IF NOT EXISTS sponsor_name TEXT,
ADD COLUMN IF NOT EXISTS sponsor_logo TEXT;

-- Create promotions/ads table for banner ads
CREATE TABLE IF NOT EXISTS promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  link_url TEXT,
  placement TEXT CHECK (placement IN ('hero', 'sidebar', 'feed', 'footer', 'popup')),
  start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  end_date TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT TRUE,
  click_count INTEGER DEFAULT 0,
  impression_count INTEGER DEFAULT 0,
  sponsor_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create index for active promotions
CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(is_active, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_events_featured ON events(is_featured, featured_until);
