-- Create Venues table
CREATE TABLE IF NOT EXISTS venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  lat FLOAT,
  lng FLOAT,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  website TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Organizers table
CREATE TABLE IF NOT EXISTS organizers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_url TEXT,
  description TEXT,
  contact_email TEXT,
  social_links JSONB, -- { "instagram": "...", "twitter": "..." }
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Tags table
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('category', 'mood', 'other')),
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Update Events table
ALTER TABLE events 
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS venue_id BIGINT REFERENCES venues(id),
ADD COLUMN IF NOT EXISTS organizer_id BIGINT REFERENCES organizers(id),
ADD COLUMN IF NOT EXISTS rules TEXT, -- Good to know info
ADD COLUMN IF NOT EXISTS source_url TEXT, -- For scraping reference
ADD COLUMN IF NOT EXISTS tags TEXT[]; -- Array of tag names or IDs

-- Create index on venue_id
CREATE INDEX IF NOT EXISTS idx_events_venue_id ON events(venue_id);
