-- =============================================================
-- 18-23 — Çok kaynaklı etkinlik alımı (event sources)
-- Idempotent. 20260928000000_schema_and_rls.sql'den SONRA çalıştırın.
-- =============================================================

-- -------------------------------------------------------------
-- 1. events: kaynak, durum ve tazelik alanları
-- -------------------------------------------------------------
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS district TEXT,
  ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'Europe/Istanbul',
  ADD COLUMN IF NOT EXISTS currency TEXT,
  ADD COLUMN IF NOT EXISTS max_price INTEGER,
  ADD COLUMN IF NOT EXISTS organizer_name TEXT,
  -- Katılım şekli / içerik türü
  ADD COLUMN IF NOT EXISTS event_kind TEXT,
  -- Yalnızca kaynağın doğruladığı durum; bilinmiyorsa 'active'
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS primary_source TEXT,
  ADD COLUMN IF NOT EXISTS geo_source TEXT,
  ADD COLUMN IF NOT EXISTS registration_url TEXT,
  ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_event_kind_check') THEN
    ALTER TABLE events ADD CONSTRAINT events_event_kind_check
      CHECK (event_kind IS NULL OR event_kind IN ('ticketed', 'free', 'registration', 'editorial', 'official'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_status_check') THEN
    ALTER TABLE events ADD CONSTRAINT events_status_check
      CHECK (status IS NULL OR status IN ('active', 'postponed', 'cancelled', 'sold_out', 'upcoming_sale', 'past', 'inactive'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_events_city_start ON events(city, start_time);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);

-- -------------------------------------------------------------
-- 2. event_sources: bir etkinliğin her kaynaktaki kaydı
--    (satış bağlantısı, fiyat, satış durumu kaynak bazında korunur)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  source_event_id TEXT NOT NULL,
  source_type TEXT NOT NULL CHECK (source_type IN ('ticketing', 'editorial', 'official')),
  url TEXT,
  ticket_url TEXT,
  title TEXT,
  start_time TIMESTAMPTZ,
  price_min INTEGER,
  price_max INTEGER,
  currency TEXT,
  availability TEXT,
  match_confidence NUMERIC(4, 3),
  needs_review BOOLEAN NOT NULL DEFAULT FALSE,
  content_hash TEXT,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source, source_event_id)
);
CREATE INDEX IF NOT EXISTS idx_event_sources_event ON event_sources(event_id);
CREATE INDEX IF NOT EXISTS idx_event_sources_review ON event_sources(needs_review) WHERE needs_review;

-- -------------------------------------------------------------
-- 3. Kaynak ayarları (admin panelinden aç/kapat) ve çalışma kayıtları
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS source_settings (
  source TEXT PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  min_interval_ms INTEGER,
  timeout_ms INTEGER,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS source_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success', 'partial', 'failed', 'skipped')),
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  duration_ms INTEGER,
  fetched INTEGER DEFAULT 0,
  inserted INTEGER DEFAULT 0,
  updated INTEGER DEFAULT 0,
  unchanged INTEGER DEFAULT 0,
  invalid INTEGER DEFAULT 0,
  needs_review INTEGER DEFAULT 0,
  errors JSONB DEFAULT '{}'::jsonb,       -- {"network": 2, "schema": 1}
  error_message TEXT
);
CREATE INDEX IF NOT EXISTS idx_source_runs_source_time ON source_runs(source, started_at DESC);

-- Son durum özeti (admin "Kaynaklar" sekmesi)
CREATE OR REPLACE VIEW source_health AS
SELECT
  s.source,
  MAX(s.started_at) AS last_run_at,
  MAX(s.started_at) FILTER (WHERE s.status IN ('success', 'partial')) AS last_success_at,
  COUNT(*) FILTER (WHERE s.started_at > NOW() - INTERVAL '7 days') AS runs_7d,
  COUNT(*) FILTER (WHERE s.started_at > NOW() - INTERVAL '7 days' AND s.status = 'failed') AS failures_7d,
  ROUND(AVG(s.duration_ms) FILTER (WHERE s.started_at > NOW() - INTERVAL '7 days'))::INTEGER AS avg_duration_ms_7d
FROM source_runs s
GROUP BY s.source;

-- -------------------------------------------------------------
-- 4. İş kilidi: aynı anda iki alım çalışmasın
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ingest_locks (
  name TEXT PRIMARY KEY,
  holder TEXT NOT NULL,
  locked_until TIMESTAMPTZ NOT NULL
);

CREATE OR REPLACE FUNCTION try_acquire_ingest_lock(p_name TEXT, p_holder TEXT, p_ttl_seconds INTEGER)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO ingest_locks (name, holder, locked_until)
  VALUES (p_name, p_holder, NOW() + make_interval(secs => p_ttl_seconds))
  ON CONFLICT (name) DO UPDATE
    SET holder = EXCLUDED.holder, locked_until = EXCLUDED.locked_until
    WHERE ingest_locks.locked_until < NOW() OR ingest_locks.holder = EXCLUDED.holder;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION release_ingest_lock(p_name TEXT, p_holder TEXT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER SET search_path = public
AS $$
  DELETE FROM ingest_locks WHERE name = p_name AND holder = p_holder;
$$;

REVOKE ALL ON FUNCTION try_acquire_ingest_lock(TEXT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION release_ingest_lock(TEXT, TEXT) FROM PUBLIC, anon, authenticated;

-- -------------------------------------------------------------
-- 5. Geocode önbelleği (Nominatim'e tekrar tekrar sormamak için)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS geocode_cache (
  query TEXT PRIMARY KEY,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  display_name TEXT,
  found BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------------
-- 6. Kullanıcı geri bildirimi: yanlış tarih/mekân bildirimi
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('wrong_date', 'wrong_venue', 'cancelled', 'wrong_price', 'other')),
  note TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'dismissed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------------
-- 7. RLS
-- -------------------------------------------------------------
ALTER TABLE event_sources   ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_runs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingest_locks    ENABLE ROW LEVEL SECURITY;
ALTER TABLE geocode_cache   ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_reports   ENABLE ROW LEVEL SECURITY;

-- Onaylı etkinliklerin kaynak bağlantıları herkese açık (satış linkleri, son görülme)
DROP POLICY IF EXISTS event_sources_public_read ON event_sources;
CREATE POLICY event_sources_public_read ON event_sources FOR SELECT
  USING (EXISTS (SELECT 1 FROM events e WHERE e.id = event_sources.event_id AND e.is_approved));

-- source_settings, source_runs, ingest_locks, geocode_cache, event_reports:
-- politika yok → yalnızca service_role (scraper, admin proxy, /api/submit).

-- source_health view'u invoker yetkisiyle çalışsın (anon'a source_runs'ı açmasın)
ALTER VIEW source_health SET (security_invoker = true);
