-- =============================================================
-- 18-23 Event Radar — tam şema + RLS
-- Idempotent: hem mevcut (restore edilmiş) hem boş projede çalışır.
-- Supabase Dashboard → SQL Editor'da tek seferde çalıştırın.
-- db_updates.sql'in yerini alır.
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -------------------------------------------------------------
-- 1. TABLOLAR
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE venues
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS contact_name TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS maps_url TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT;

CREATE TABLE IF NOT EXISTS organizers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE organizers
  ADD COLUMN IF NOT EXISTS logo_url TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS contact_email TEXT,
  ADD COLUMN IF NOT EXISTS social_links JSONB;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('category', 'mood', 'other')),
  icon TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS venue_name TEXT,
  ADD COLUMN IF NOT EXISTS venue_id BIGINT REFERENCES venues(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS organizer_id BIGINT REFERENCES organizers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS maps_url TEXT,
  ADD COLUMN IF NOT EXISTS price TEXT,
  ADD COLUMN IF NOT EXISTS min_price INTEGER,
  ADD COLUMN IF NOT EXISTS ticket_url TEXT,
  ADD COLUMN IF NOT EXISTS ticket_details JSONB,
  ADD COLUMN IF NOT EXISTS ticket_sources JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[],
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS local_image_url TEXT,
  ADD COLUMN IF NOT EXISTS media_url TEXT,
  ADD COLUMN IF NOT EXISTS rules TEXT,
  ADD COLUMN IF NOT EXISTS source_url TEXT,
  ADD COLUMN IF NOT EXISTS is_approved BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sold_out BOOLEAN DEFAULT FALSE,
  -- AI zenginleştirme
  ADD COLUMN IF NOT EXISTS summary TEXT,
  ADD COLUMN IF NOT EXISTS ai_tags TEXT[],
  ADD COLUMN IF NOT EXISTS ai_mood TEXT,
  ADD COLUMN IF NOT EXISTS is_ai_processed BOOLEAN DEFAULT FALSE,
  -- Öne çıkarma
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS featured_until TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS feature_priority INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sponsor_name TEXT,
  ADD COLUMN IF NOT EXISTS sponsor_logo TEXT;

CREATE INDEX IF NOT EXISTS idx_events_venue_id ON events(venue_id);
CREATE INDEX IF NOT EXISTS idx_events_featured ON events(is_featured, featured_until);
CREATE INDEX IF NOT EXISTS idx_events_approved_start ON events(is_approved, start_time);

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS preferences TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS playlist_url TEXT,
  ADD COLUMN IF NOT EXISTS music_vibe TEXT,
  ADD COLUMN IF NOT EXISTS kvkk_accepted_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS favorites (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorites_user_event ON favorites(user_id, event_id);

CREATE TABLE IF NOT EXISTS analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  category TEXT,
  action_type TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS venue_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name TEXT NOT NULL,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  event_url TEXT,
  notes TEXT,
  contact_email TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS follows (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  entity_type TEXT,
  entity_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, entity_type, entity_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT,
  message TEXT,
  link TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scraper_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scraper_name TEXT NOT NULL,
  status TEXT CHECK (status IN ('running', 'success', 'failed')),
  events_count INTEGER DEFAULT 0,
  error_message TEXT,
  duration_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  click_type TEXT CHECK (click_type IN ('view', 'ticket', 'directions', 'share', 'calendar', 'restaurant')),
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_event_clicks_event_id ON event_clicks(event_id);
CREATE INDEX IF NOT EXISTS idx_event_clicks_created_at ON event_clicks(created_at);

CREATE TABLE IF NOT EXISTS event_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  is_verified BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (event_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_event_reviews_event_id ON event_reviews(event_id);
CREATE INDEX IF NOT EXISTS idx_event_reviews_status ON event_reviews(status);

CREATE TABLE IF NOT EXISTS promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  link_url TEXT,
  placement TEXT CHECK (placement IN ('hero', 'sidebar', 'feed', 'footer', 'popup')),
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,
  click_count INTEGER DEFAULT 0,
  impression_count INTEGER DEFAULT 0,
  sponsor_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_promotions_active ON promotions(is_active, start_date, end_date);

-- -------------------------------------------------------------
-- 2. UPSERT İÇİN UNIQUE KISITLAR
-- Scraper'lar onConflict: 'source_url', admin venue upload onConflict: 'name' kullanır.
-- Mevcut veride tekrar eden kayıt varsa bu adım hata verir; önce şu sorgularla temizleyin:
--   SELECT source_url, COUNT(*) FROM events WHERE source_url IS NOT NULL GROUP BY 1 HAVING COUNT(*) > 1;
--   SELECT name, COUNT(*) FROM venues GROUP BY 1 HAVING COUNT(*) > 1;
-- -------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_events_source_url ON events(source_url);
CREATE UNIQUE INDEX IF NOT EXISTS uq_venues_name ON venues(name);

-- -------------------------------------------------------------
-- 3. VIEW'LAR
-- -------------------------------------------------------------

-- Popülerlik sıralaması için favori sayıları (kimin favorilediğini açığa çıkarmaz)
CREATE OR REPLACE VIEW event_favorite_counts AS
SELECT event_id, COUNT(*)::INTEGER AS favorite_count
FROM favorites
GROUP BY event_id;

CREATE OR REPLACE VIEW event_ratings AS
SELECT event_id, COUNT(*) AS review_count, ROUND(AVG(rating)::numeric, 1) AS avg_rating
FROM event_reviews
WHERE status = 'approved'
GROUP BY event_id;

GRANT SELECT ON event_favorite_counts, event_ratings TO anon, authenticated;

-- -------------------------------------------------------------
-- 4. TRIGGER'LAR
-- -------------------------------------------------------------

-- Yeni kullanıcı → profiles satırı
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, kvkk_accepted_at)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    CASE WHEN NEW.raw_user_meta_data ? 'kvkk_accepted_at'
         THEN (NEW.raw_user_meta_data->>'kvkk_accepted_at')::timestamptz END
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Restore öncesi oluşmuş ama profili olmayan kullanıcılar
INSERT INTO profiles (id, email, full_name)
SELECT u.id, u.email, split_part(u.email, '@', 1) FROM auth.users u
ON CONFLICT (id) DO NOTHING;

-- auth.users üzerinde başka isimli eski bir profil trigger'ı varsa çift insert olur; uyar.
DO $
DECLARE t RECORD;
BEGIN
  FOR t IN SELECT tgname FROM pg_trigger
           WHERE tgrelid = 'auth.users'::regclass AND NOT tgisinternal AND tgname <> 'on_auth_user_created'
  LOOP
    RAISE NOTICE 'auth.users üzerinde ek trigger var: % — profil oluşturuyorsa kaldırın (DROP TRIGGER % ON auth.users)', t.tgname, t.tgname;
  END LOOP;
END $;

-- Takip edilen mekâna yeni onaylı etkinlik → bildirim.
-- SECURITY DEFINER: notifications tablosuna RLS'e takılmadan yazar.
CREATE OR REPLACE FUNCTION handle_new_event_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NEW.is_approved AND (TG_OP = 'INSERT' OR NOT COALESCE(OLD.is_approved, FALSE)) THEN
    INSERT INTO notifications (user_id, title, message, link)
    SELECT f.user_id,
           'Yeni Etkinlik: ' || NEW.venue_name,
           NEW.title || ' etkinliği eklendi! Biletler tükenmeden göz at.',
           '/etkinlik/' || NEW.id
    FROM follows f
    WHERE f.entity_type = 'venue' AND f.entity_id = NEW.venue_name;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_event_created ON events;
CREATE TRIGGER on_event_created
AFTER INSERT OR UPDATE OF is_approved ON events
FOR EACH ROW EXECUTE FUNCTION handle_new_event_notification();

-- -------------------------------------------------------------
-- 5. ROW LEVEL SECURITY
-- service_role anahtarı RLS'i atlar: admin paneli (sunucu proxy'si)
-- ve scraper'lar onunla çalışır. Aşağıdakiler yalnızca anon/authenticated içindir.
-- -------------------------------------------------------------

ALTER TABLE events              ENABLE ROW LEVEL SECURITY;
ALTER TABLE venues              ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags                ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles            ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites           ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics           ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_applications  ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_suggestions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows             ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications       ENABLE ROW LEVEL SECURITY;
ALTER TABLE scraper_logs        ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_clicks        ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_reviews       ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions          ENABLE ROW LEVEL SECURITY;

-- Eski / elle eklenmiş politikaları temizle (ör. "Enable all access")
DO $$
DECLARE p RECORD;
BEGIN
  FOR p IN
    SELECT schemaname, tablename, policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename IN (
      'events','venues','organizers','tags','profiles','favorites','analytics',
      'venue_applications','event_suggestions','follows','notifications',
      'scraper_logs','event_clicks','event_reviews','promotions')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', p.policyname, p.schemaname, p.tablename);
  END LOOP;
END $$;

-- events: herkes onaylıları okur; giriş yapmış kullanıcı onaysız öneri ekler (/venue)
CREATE POLICY events_public_read ON events FOR SELECT
  USING (is_approved = TRUE);
CREATE POLICY events_owner_read ON events FOR SELECT TO authenticated
  USING (owner_id = auth.uid());
CREATE POLICY events_user_submit ON events FOR INSERT TO authenticated
  WITH CHECK (owner_id = auth.uid() AND is_approved = FALSE AND COALESCE(is_featured, FALSE) = FALSE);

-- Referans tablolar: herkese açık okuma. venues'ta iletişim kolonları gizli (aşağıda).
CREATE POLICY venues_public_read ON venues FOR SELECT USING (TRUE);
CREATE POLICY organizers_public_read ON organizers FOR SELECT USING (TRUE);
CREATE POLICY tags_public_read ON tags FOR SELECT USING (TRUE);
CREATE POLICY promotions_public_read ON promotions FOR SELECT
  USING (is_active = TRUE AND (end_date IS NULL OR end_date > NOW()));

-- profiles: yalnızca kendi satırı
CREATE POLICY profiles_self_read ON profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY profiles_self_insert ON profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY profiles_self_update ON profiles FOR UPDATE TO authenticated
  USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- favorites / follows: yalnızca kendi satırları (sayılar event_favorite_counts view'undan)
CREATE POLICY favorites_self_all ON favorites FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY follows_self_all ON follows FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- notifications: kendi bildirimini okur / okundu işaretler
CREATE POLICY notifications_self_read ON notifications FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY notifications_self_update ON notifications FOR UPDATE TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- analytics / event_clicks: anonim yazma, okuma yok
CREATE POLICY analytics_insert ON analytics FOR INSERT
  WITH CHECK (action_type IN ('favorite', 'share', 'calendar', 'ticket', 'view', 'directions'));
CREATE POLICY event_clicks_insert ON event_clicks FOR INSERT WITH CHECK (TRUE);

-- event_reviews: onaylıları herkes okur; kullanıcı kendi yorumunu 'pending' olarak ekler
CREATE POLICY reviews_public_read ON event_reviews FOR SELECT USING (status = 'approved');
CREATE POLICY reviews_self_read ON event_reviews FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY reviews_self_insert ON event_reviews FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND status = 'pending' AND COALESCE(is_verified, FALSE) = FALSE);

-- venue_applications, event_suggestions, scraper_logs: politika yok →
-- anon/authenticated hiçbir şey yapamaz. Yazma /api/submit (service_role) üzerinden.

-- venues iletişim bilgileri (kişisel veri) herkese açık olmasın
REVOKE SELECT ON venues FROM anon, authenticated;
GRANT SELECT (id, name, address, lat, lng, website, maps_url, city, created_at) ON venues TO anon, authenticated;
